
pipeline {
    agent {
        node 'gpu480'
    }
    environment {
        PYTHONIOENCODING='utf-8'
        PYTHONPATH = '.'
    }
    parameters{
        string(name: 'filename', defaultValue: 'T21imgs_TOURISM_general_general_k11_tj_20210702', description: '已标注文件名', trim: true)
    }

    stages {
        stage('Build') {
            steps {
                dir('/opt/jenkins/workspace/poc/callresult1v1/SendLable1V1') {
                    sh('whoami')
                    sh('pwd')
                    sh('export PYTHONPATH=.')
                    sh('export PYTHONIOENCODING=utf-8')
                    sh('python3 callresult/cal_result.py --filename ${filename} ')
                    
                }
            }
        }
    }
}
